# Site settings
title: 李理的博客
SEOTitle: 李理的博客
header-img: img/home-bg.jpg
email: fancyerii@gmail.com
description: ""
keyword: ""
url: "http://fancyerii.github.io"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'
excerpt_separator: "<!--more-->"


# SNS settings
RSS: true
#weibo_username:     huxpro
#zhihu_username:     huxpro
github_username:    fancyerii
#twitter_username:  huxpro
#facebook_username:  huxpro



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: fancyerii

# Duoshuo settings
duoshuo_username:  
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 1adf2d3145a435baa683d84388135812
# Google Analytics
# ga_track_id: 'UA-133955198-1'            # Format: UA-xxxxxx-xx
# ga_domain: fancyerii.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "读读论文，写写代码。"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

collections:
  books:
    output: true

  wang:
    output: true

  kaldi:
    output: true

  kaldidoc:
    output: true

  dev287x:
    output: true

  wfst:
    output: true

# Friends
friends: [
    {
        title: "Li Li",
        href: "http://fancyerii.github.io"
    }
]
